# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
schema = "spotify_schema"

[migrations_directory]
dir = "/home/hemraj/RustroverProjects/spotify-music/migrations"
