-- Your SQL goes here
CREATE TABLE "spotify_schema"."song_information"(
	"song_id" SERIAL PRIMARY KEY,
	"artist" VARCHAR NOT NULL,
    "song" VARCHAR NOT NULL,
	"text" TEXT NOT NULL,
	"length" VARCHAR NOT NULL,
	"emotion" VARCHAR NOT NULL,
	"genre" VARCHAR NOT NULL,
	"album" VARCHAR NOT NULL,
	"release_date" VARCHAR NOT NULL,
	"key" VARCHAR NOT NULL,
	"tempo" FLOAT8 NOT NULL,
	"loudness" FLOAT8 NOT NULL,
	"time_signature" VARCHAR NOT NULL,
	"explicit" VARCHAR NOT NULL,
	"popularity" INT4 NOT NULL,
	"energy" INT4 NOT NULL,
	"danceability" INT4 NOT NULL,
	"positiveness" INT4 NOT NULL,
	"speechiness" INT4 NOT NULL,
	"liveness" INT4 NOT NULL,
	"acousticness" INT4 NOT NULL,
	"instrumentalness" INT4 NOT NULL,
	"good_for_party" BOOL NOT NULL,
	"good_for_work" BOOL NOT NULL,
    "good_for_relaxation" BOOL NOT NULL,
	"good_for_exercise" BOOL NOT NULL,
	"good_for_running" BOOL NOT NULL,
	"good_for_yoga" BOOL NOT NULL,
	"good_for_driving" BOOL NOT NULL,
	"good_for_social_gatherings" BOOL NOT NULL,
	"good_for_morning_routine" BOOL NOT NULL,
	"similar_artist_1" VARCHAR NOT NULL,
	"similar_song_1" VARCHAR NOT NULL,
	"similarity_score_1" FLOAT8 NOT NULL,
	"similar_artist_2" VARCHAR NOT NULL,
	"similar_song_2" VARCHAR NOT NULL,
	"similarity_score_2" FLOAT8 NOT NULL,
	"similar_artist_3" VARCHAR NOT NULL,
	"similar_song_3" VARCHAR NOT NULL,
	"similarity_score_3" FLOAT8 NOT NULL,
	"unique_id" VARCHAR NOT NULL,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

