// @generated automatically by Diesel CLI.

diesel::table! {
    spotify_schema.song_information (song_id) {
        song_id -> Int4,
        artist -> Varchar,
        song -> Varchar,
        text -> Text,
        length -> Varchar,
        emotion -> Varchar,
        genre -> Varchar,
        album -> Varchar,
        release_date -> Varchar,
        key -> Varchar,
        tempo -> Float8,
        loudness -> Float8,
        time_signature -> Varchar,
        explicit -> Varchar,
        popularity -> Int4,
        energy -> Int4,
        danceability -> Int4,
        positiveness -> Int4,
        speechiness -> Int4,
        liveness -> Int4,
        acousticness -> Int4,
        instrumentalness -> Int4,
        good_for_party -> Bool,
        good_for_work -> Bool,
        good_for_relaxation -> Bool,
        good_for_exercise -> Bool,
        good_for_running -> Bool,
        good_for_yoga -> Bool,
        good_for_driving -> Bool,
        good_for_social_gatherings -> Bool,
        good_for_morning_routine -> Bool,
        similar_artist_1 -> Varchar,
        similar_song_1 -> Varchar,
        similarity_score_1 -> Float8,
        similar_artist_2 -> Varchar,
        similar_song_2 -> Varchar,
        similarity_score_2 -> Float8,
        similar_artist_3 -> Varchar,
        similar_song_3 -> Varchar,
        similarity_score_3 -> Float8,
        unique_id -> Varchar,
        created_at -> Nullable<Timestamp>,
    }
}
